
import { CategoryInfo } from './types';

// Radio browser API mirrors
export const RADIO_BROWSER_MIRRORS = [
    'https://all.api.radio-browser.info/json/stations',
    'https://de1.api.radio-browser.info/json/stations',
    'https://at1.api.radio-browser.info/json/stations',
    'https://nl1.api.radio-browser.info/json/stations',
    'https://fr1.api.radio-browser.info/json/stations',
    'https://uk1.api.radio-browser.info/json/stations'
];

/**
 * FIX: Added missing constants required by App.tsx
 */
export const DEFAULT_VOLUME = 0.5;

export const GENRES: CategoryInfo[] = [
    { id: 'jazz', name: 'Jazz', color: 'from-amber-400 to-orange-600', description: 'Smooth rhythms and improvisations.' },
    { id: 'rock', name: 'Rock', color: 'from-red-600 to-purple-900', description: 'Energetic beats and powerful guitars.' },
    { id: 'classical', name: 'Classical', color: 'from-blue-200 to-slate-400', description: 'Timeless masterpieces and symphonies.' },
    { id: 'electronic', name: 'Electronic', color: 'from-cyan-400 to-blue-600', description: 'Synthesized sounds and modern beats.' },
    { id: 'hiphop', name: 'Hip Hop', color: 'from-green-400 to-yellow-600', description: 'Rhythmic speech and street culture.' },
    { id: 'pop', name: 'Pop', color: 'from-pink-400 to-rose-600', description: 'Catchy melodies and chart-topping hits.' }
];

export const ERAS: CategoryInfo[] = [
    { id: '60s', name: '60s', color: 'from-yellow-300 to-orange-500', description: 'The era of peace, love, and rock & roll.' },
    { id: '70s', name: '70s', color: 'from-orange-500 to-red-600', description: 'Disco, funk, and the rise of stadium rock.' },
    { id: '80s', name: '80s', color: 'from-fuchsia-500 to-indigo-600', description: 'Synth-pop, big hair, and MTV classics.' },
    { id: '90s', name: '90s', color: 'from-teal-400 to-blue-500', description: 'Grunge, rave culture, and the golden age of R&B.' },
    { id: '00s', name: '00s', color: 'from-slate-400 to-slate-600', description: 'The digital revolution and fusion genres.' }
];

export const MOODS: CategoryInfo[] = [
    { id: 'chill', name: 'Chill', type: 'mood', color: 'from-blue-400 to-indigo-500', description: 'Relaxing tunes for a peaceful mind.' },
    { id: 'energy', name: 'Energy', type: 'mood', color: 'from-yellow-400 to-orange-500', description: 'Upbeat tracks to get you moving.' },
    { id: 'focus', name: 'Focus', type: 'mood', color: 'from-emerald-400 to-teal-600', description: 'Background music for work and study.' },
    { id: 'romantic', name: 'Romantic', type: 'mood', color: 'from-rose-400 to-pink-600', description: 'Melodies for special moments.' },
    { id: 'dark', name: 'Club', type: 'mood', color: 'from-slate-800 to-black', description: 'Powerful beats for club enthusiasts.' }
];

export const TRANSLATIONS: any = {
    en: {
        listeningTo: "Listening to",
        searchPlaceholder: "Search...",
        myCollection: "My Collection",
        popularStations: "Popular Stations",
        discoverPeople: "Discover People",
        messages: "Messages",
        contacts: "Contacts",
        knock: "Knock",
        connected: "Connected",
        messagePlaceholder: "Message...",
        eq: "EQ",
        look: "Look",
        sleep: "Sleep",
        resetFlat: "Reset Flat",
        appAppearance: "App Appearance",
        sleepTimer: "Sleep Timer",
        turnOffTimer: "Turn Off Timer",
        whoAreYou: "Welcome to StreamFlow",
        createProfile: "Create your profile to join the global community of listeners.",
        displayName: "Display Name",
        age: "Age",
        country: "Country",
        city: "City",
        gender: "Gender",
        male: "Male",
        female: "Female",
        other: "Other",
        any: "Any",
        joinCommunity: "Start Listening",
        uploadPhoto: "Upload Photo",
        call: "Call",
        calling: "Calling...",
        endCall: "End Call",
        videoCall: "Video Call",
        saveContact: "Save to Contacts",
        editName: "Edit Name",
        save: "Save",
        cancel: "Cancel",
        genres: "Genres",
        eras: "Eras",
        mood: "Mood",
        moods: "Mood",
        favorites: "Favorites",
        settings: "Settings",
        language: "Language",
        recording: "Recording...",
        tapToSpeak: "Tap to speak",
        tapToStop: "Tap to stop",
        failedToLoadStations: "Failed to load stations.",
        corsWarningVisualizer: "Visualizer and EQ are disabled for this station due to stream security settings (CORS).",
        chatSettings: "Chat Settings",
        filterBy: "Filter by",
        ageRange: "Age Range",
        preferredGender: "Preferred Gender",
        blockUser: "Block User",
        yellowWarning: "Yellow Warning",
        redBlock: "Permanent Block",
        warningNotice: "The user has been issued a yellow warning.",
        blockNotice: "The user has been permanently blocked and banned.",
        bannedMessage: "Your account is temporarily restricted (1 day) due to user reports.",
        safetyLevel: "Safety Status",
        help: "Help",
        manual: "Manual",
        tutorial: "Tutorial",
        startTutorial: "Start Interactive Lesson",
        skip: "Skip",
        next: "Next",
        gotIt: "Got it!",
        tutorialWelcome: "Welcome to StreamFlow!",
        tutorialStep1: "In the sidebar, you can explore stations by Genre or Era. Your favorite stations are also kept here.",
        tutorialStep2: "Browse thousands of stations in the main list. Click any card to instantly start the live stream.",
        tutorialStep3: "The player bar shows your current station. Use it to control playback, volume, and view the visualizer.",
        tutorialStep4: "Open the Tools panel to customize the Equalizer, change the App Theme, or set a Sleep Timer.",
        tutorialStep5: "Connect with other listeners! Use the Chat to find people by age, city, and country.",
        manualTitle: "User Manual",
        manualIntro: "StreamFlow is a modern radio streaming platform. Discipline and respect are our core values.",
        manualSection1: "1. Navigation: Choose stations by genre or era. Search for specific names or tags.",
        manualSection2: "2. Audio: High-quality streams. If a station doesn't play, it might be due to regional restrictions.",
        manualSection3: "3. Sound Control: Use EQ to adjust frequencies. Visualizer shows real-time audio data.",
        manualSection4: "4. Communication Code: We allow expressive and frank communication only if both parties agree. However, any user can block another at any time if they feel uncomfortable.",
        manualSection5: "5. Strict Bans: Insults, sexual violence, pornography, or nudity lead to a permanent ban. Selling weapons or drugs is strictly prohibited. Communication with minors is forbidden. Mutual respect is mandatory. All illegal actions are forbidden and reported.",
        discoveryDrum: "Discovery Drum",
        agreeToMeet: "Agree to Meet",
        lookingForMatch: "Looking for a match...",
        newMatchFound: "New Match Found!",
        match: "Match",
        found: "Found",
        listenersOnline: "Listeners Online",
        adjustFilters: "Adjust Filters",
        minAge: "Min Age",
        maxAge: "Max Age",
        search: "Search",
        blockConfirm: "Block this user for 24 hours?",
        soundNotifications: "Sound Notifications",
        on: "On",
        off: "Off",
        activeChats: "Active Chats",
        downloader: "Music Downloader",
        hqDownload: "Download HQ",
        communityCode: "Community Code",
        iAgree: "I Agree to the Rules",
        rulesTitle: "Strict Discipline Rules",
        rulesIntro: "By entering this chat, you accept a policy of ZERO TOLERANCE for violations:",
        rule1: "NO MINORS (18+ ONLY): Chat is strictly for adults. ANY attempt to communicate with minors or access by minors will result in a PERMANENT LIFETIME BAN and application closure for your device.",
        rule2: "Content Control: Nudity, pornography, and sexual violence in any format (photo/video/text) lead to an IMMEDIATE PERMANENT BAN.",
        rule3: "Criminal Offenses: Selling, promoting, or distributing weapons, drugs, or narcotic substances will result in a lifetime ban and potential report to authorities.",
        rule4: "Consent & Respect: Profanity and frank language are allowed ONLY if mutually agreed. You must respect others and have the right to block anyone instantly.",
        visualizer: "Visualizer",
        vizGalaxy: "Galaxy",
        vizRings: "Quantum Rings",
        vizBubbles: "Bubbles",
        vizLines: "Neon Lines",
        vizBars: "Classic",
        vizDancer: "Stage Dancer",
        vizTrio: "Trio Dancers",
        vizJourney: "Universal Journey"
    },
    ru: {
        listeningTo: "Сейчас играет",
        searchPlaceholder: "Поиск...",
        myCollection: "Моя коллекция",
        popularStations: "Популярные станции",
        discoverPeople: "Найти людей",
        messages: "Сообщения",
        contacts: "Контакты",
        knock: "Постучать",
        connected: "Подключено",
        messagePlaceholder: "Сообщение...",
        eq: "Эквалайзер",
        look: "Вид",
        sleep: "Таймер",
        resetFlat: "Сброс",
        appAppearance: "Внешний вид",
        sleepTimer: "Таймер сна",
        turnOffTimer: "Выключить таймер",
        whoAreYou: "Добро пожаловать в StreamFlow",
        createProfile: "Создайте профиль, чтобы стать частью мирового сообщества слушателей.",
        displayName: "Ваше имя",
        age: "Возраст",
        country: "Страна",
        city: "Город",
        gender: "Пол",
        male: "Мужской",
        female: "Женский",
        other: "Другой",
        any: "Любой",
        joinCommunity: "Войти в систему",
        uploadPhoto: "Загрузить фото",
        call: "Позвонить",
        calling: "Звонок...",
        endCall: "Завершить",
        videoCall: "Видеозвонок",
        saveContact: "В контакты",
        editName: "Изменить имя",
        save: "Сохранить",
        cancel: "Отмена",
        genres: "Жанры",
        eras: "Эпохи",
        mood: "Настроение",
        moods: "Настроение",
        favorites: "Избранное",
        settings: "Настройки",
        language: "Язык",
        recording: "Запись...",
        tapToSpeak: "Нажмите, чтобы говорить",
        tapToStop: "Нажмите, чтобы остановить",
        failedToLoadStations: "Не удалось загрузить станции.",
        corsWarningVisualizer: "Визуализатор и эквалайзер отключены для этой станции из-за настроек безопасности потока (CORS).",
        chatSettings: "Настройки чата",
        filterBy: "Фильтровать по",
        ageRange: "Возраст",
        preferredGender: "Предпочтительный пол",
        blockUser: "Заблокировать",
        yellowWarning: "Желтый уровень",
        redBlock: "Полная блокировка",
        warningNotice: "Пользователю вынесено предупреждение (Желтый уровень).",
        blockNotice: "Пользователь заблокирован навсегда.",
        bannedMessage: "Ваш аккаунт временно ограничен (на 1 день) из-за жалоб пользователей.",
        safetyLevel: "Уровень безопасности",
        help: "Помощь",
        manual: "Инструкция",
        tutorial: "Урок",
        startTutorial: "Начать обучение",
        skip: "Пропустить",
        next: "Далее",
        gotIt: "Понятно!",
        tutorialWelcome: "Добро пожаловать в StreamFlow!",
        tutorialStep1: "В боковом меню можно выбирать станции по жанрам или эпохам. Здесь же хранятся ваши избранные каналы.",
        tutorialStep2: "В основном списке тысячи станций. Просто нажмите на любую карточку, чтобы запустить прямой эфир.",
        tutorialStep3: "Панель игрока внизу показывает текущую станцию. Тут можно управлять громкостью и видеть визуализатор.",
        tutorialStep4: "В панели инструментов можно настроить эквалайзер, изменить тему оформления или поставить таймер сна.",
        tutorialStep5: "Общайтесь с другими слушателями! Используйте чат, чтобы найти людей по возрасту, городу или стране.",
        manualTitle: "Руководство пользователя",
        manualIntro: "StreamFlow — современная платформа. Дисциплина и уважение — наши главные ценности.",
        manualSection1: "1. Навигация: Выбирайте жанры и эпохи. Поиск поможет найти любимую волну.",
        manualSection2: "2. Звук: Мы используем лучшие серверы. Если станция не играет, это может быть из-за прав вещания.",
        manualSection3: "3. Настройка: Эквалайзер и темы оформления позволяют сделать приложение индивидуальным.",
        manualSection4: "4. Кодекс общения: Допускается откровенное общение и неформальный язык только при взаимном согласии. Однако любой пользователь может заблокировать другого в любой момент.",
        manualSection5: "5. Строгие запреты: Оскорбления, сексуальное насилие, порнография или нагота ведут к пожизненному бану. Продажа оружия или наркотиков строго запрещена.",
        discoveryDrum: "Барабан открытий",
        agreeToMeet: "Согласиться на встречу",
        lookingForMatch: "Ищем подходящую пару...",
        newMatchFound: "Найдено новое совпадение!",
        match: "Пара",
        found: "Найдено",
        listenersOnline: "Слушателей в сети",
        adjustFilters: "Настроить фильтры",
        minAge: "Мин. возраст",
        maxAge: "Макс. возраст",
        search: "Поиск",
        blockConfirm: "Заблокировать пользователя на 24 часа?",
        soundNotifications: "Звуковые уведомления",
        on: "Вкл",
        off: "Выкл",
        activeChats: "Активные чаты",
        downloader: "Загрузчик музыки",
        hqDownload: "Скачать в HQ",
        communityCode: "Кодекс сообщества",
        iAgree: "Я согласен с правилами",
        rulesTitle: "Правила строгой дисциплины",
        rulesIntro: "Входя в этот чат, вы принимаете политику НУЛЕВОЙ ТОЛЕРАНТНОСТИ к нарушениям:",
        rule1: "НЕТ НЕСОВЕРШЕННОЛЕТНИМ (ТОЛЬКО 18+): Чат строго для взрослых. ЛЮБАЯ попытка общения с несовершеннолетними приведет к ПОЖИЗНЕННОМУ БАНУ.",
        rule2: "Контроль контента: Нагота, порнография и сексуальное насилие в любом формате ведут к НЕМЕДЛЕННОМУ ПОЖИЗНЕННОМУ БАНУ.",
        rule3: "Уголовные преступления: Продажа, продвижение или распространение оружия, наркотиков или наркотических веществ приведет к бану.",
        rule4: "Согласие и уважение: Ненормативная лексика и откровенный язык разрешены ТОЛЬКО при взаимном согласии.",
        visualizer: "Визуализация",
        vizGalaxy: "Галактика",
        vizRings: "Квантовые кольца",
        vizBubbles: "Пузыри",
        vizLines: "Неоновые линии",
        vizBars: "Классика",
        vizDancer: "Танцор",
        vizTrio: "Трио танцоров",
        vizJourney: "Путешествие по Вселенной"
    },
    kk: {
        listeningTo: "Тыңдалуда",
        searchPlaceholder: "Іздеу...",
        myCollection: "Менің коллекциям",
        popularStations: "Танымал станциялар",
        discoverPeople: "Адамдарды табу",
        messages: "Хабарламалар",
        contacts: "Контактілер",
        knock: "Тықылдату",
        connected: "Қосылды",
        messagePlaceholder: "Хабарлама...",
        eq: "Эквалайзер",
        look: "Түр",
        sleep: "Таймер",
        resetFlat: "Қалпына келтіру",
        appAppearance: "Сыртқы түрі",
        sleepTimer: "Ұйқы таймері",
        turnOffTimer: "Таймерді өшіру",
        whoAreYou: "StreamFlow-ға қош келдіңіз",
        createProfile: "Тыңдаушылардың жаһандық қауымдастығына қосылу үшін профиль жасаңыз.",
        displayName: "Көрсетілетін есім",
        age: "Жас",
        country: "Ел",
        city: "Қала",
        gender: "Жынысы",
        male: "Еркек",
        female: "Әйел",
        other: "Басқа",
        any: "Кез келген",
        joinCommunity: "Қосылу",
        uploadPhoto: "Сурет жүктеу",
        call: "Қоңырау шалу",
        calling: "Қоңырау шалынуда...",
        endCall: "Аяқтау",
        videoCall: "Бейнеқоңырау",
        saveContact: "Контактілерге сақтау",
        editName: "Есімді өзгерту",
        save: "Сақтау",
        cancel: "Болдырмау",
        genres: "Жанрлар",
        eras: "Дәуірлер",
        mood: "Көңіл-күй",
        moods: "Көңіл-күй",
        favorites: "Таңдаулылар",
        settings: "Параметрлер",
        language: "Тіл",
        recording: "Зазылуда...",
        tapToSpeak: "Сөйлеу үшін басыңыз",
        tapToStop: "Тоқтату үшін басыңыз",
        failedToLoadStations: "Станцияларды жүктеу сәтсіз аяқталды.",
        corsWarningVisualizer: "Бұл станция үшін визуализатор және эквалайзер өшірілген.",
        chatSettings: "Чат параметрлері",
        filterBy: "Сүзгілеу",
        ageRange: "Жас аралығы",
        preferredGender: "Қалаулы жыныс",
        blockUser: "Блоктау",
        yellowWarning: "Сары ескерту",
        redBlock: "Тұрақты блоктау",
        warningNotice: "Пайдаланушыға сары ескерту берілді.",
        blockNotice: "Пайдаланушы біржола блокталды.",
        bannedMessage: "Сіздің аккаунтыңыз уақытша шектелген (1 күн).",
        safetyLevel: "Қауіпсіздік деңгейі",
        help: "Қолдау",
        manual: "Нұсқаулық",
        tutorial: "Сабақ",
        startTutorial: "Оқытуды бастау",
        skip: "Өткізіп жіберу",
        next: "Келесі",
        gotIt: "Түсінікті!",
        tutorialWelcome: "StreamFlow-ға қош келдіңіз!",
        tutorialStep1: "Бүйірлік мәзірде жанр немесе дәуір бойынша станцияларды зерттей аласыз. Таңдаулы станциялар осында сақталады.",
        tutorialStep2: "Негізгі тізімдегі мыңдаған станцияларды қараңыз. Кез келген карточканы басып, тікелей эфирді бастаңыз.",
        tutorialStep3: "Ойнатқыш панелі ағымдағы станцияны көрсетеді. Оны дыбысты, ойнатуды және визуализаторды басқару үшін пайдаланыңыз.",
        tutorialStep4: "Эквалайзерді реттеу, тақырыпты өзгерту немесе ұйқы таймерін орнату үшін Құралдар панелін ашыңыз.",
        tutorialStep5: "Басқа тыңдаушылармен байланысыңыз! Жасы, қаласы және елі бойынша адамдарды табу үшін Чатты пайдаланыңыз.",
        manualTitle: "Пайдаланушы нұсқаулығы",
        manualIntro: "StreamFlow — заманауи радио ағынды платформасы. Тәртіп пен құрмет — біздің негізгі құндылықтарымыз.",
        manualSection1: "1. Навигация: Жанр немесе дәуір бойынша станцияларды таңдаңыз. Нақты атаулар неметер тегтер бойынша іздеңіз.",
        manualSection2: "2. Аудио: Жоғары сапалы ағындар. Егер станция ойнамаса, бұл аймақтық шектеулерге байланысты болуы мүмкін.",
        manualSection3: "3. Дыбысты басқару: Жиіліктерді реттеу үшін эквалайзерді пайдаланыңыз. Визуализатор нақты уақыттағы аудио деректерді көрсетеді.",
        manualSection4: "4. Байланыс кодексі: Екі тарап келіссе ғана еркін сөйлесуге рұқсат етіледі. Дегенмен, кез келген пайдаланушы өзін жайсыз сезінсе, кез келген уақытта басқасын блоктай алады.",
        manualSection5: "5. Қатаң тыйымдар: Балағат сөздер, сексуалдық зорлық-зомбылық немесе жалаңаштық тұрақты блоктауға әкеледі. Қару немесе есірткі сатуға қатаң тыйым салынады.",
        discoveryDrum: "Жаңалықтар барабаны",
        agreeToMeet: "Кездесуге келісу",
        lookingForMatch: "Сәйкестік ізделуде...",
        newMatchFound: "Жаңа сәйкестік табылды!",
        match: "Сәйкестік",
        found: "Табылды",
        listenersOnline: "Тыңдаушылар онлайн",
        adjustFilters: "Сүзгілерді реттеу",
        minAge: "Мин. жас",
        maxAge: "Макс. жас",
        search: "Іздеу",
        blockConfirm: "Пайдаланушыны 24 сағатқа блоктау керек пе?",
        soundNotifications: "Дыбыстық хабарландырулар",
        on: "Қосулы",
        off: "Өшірулі",
        activeChats: "Белсенді чаттар",
        downloader: "Музыка жүктеуші",
        hqDownload: "HQ жүктеу",
        communityCode: "Қауымдастық кодексі",
        iAgree: "Мен ережелермен келісемін",
        rulesTitle: "Қатаң тәртіп ережелері",
        rulesIntro: "Бұл чатқа кіру арқылы сіз келесі ережелерді қабылдайсыз:",
        rule1: "КӘМЕЛЕТКЕ ТОЛМАҒАНДАРҒА ТЫЙЫМ САЛЫНАДЫ (ТЕК 18+).",
        rule2: "Контентті бақылау: Порнографияға тыйым салынады.",
        rule3: "Қылмыстық құқық бұзушылықтар: Қару немесе есірткі сатуға тыйым салынады.",
        rule4: "Келісім және құрмет: Бір-біріңізді құрметтеңіз.",
        visualizer: "Визуализация",
        vizGalaxy: "Галактика",
        vizRings: "Кванттық сақиналар",
        vizBubbles: "Көпіршіктер",
        vizLines: "Неонды сызықтар",
        vizBars: "Классика",
        vizDancer: "Биші",
        vizTrio: "Үштік бишілер",
        vizJourney: "Әлемдік саяхат"
    },
    ky: {
        listeningTo: "Угулуп жатат",
        searchPlaceholder: "Издөө...",
        myCollection: "Менин коллекциям",
        popularStations: "Популярдуу станциялар",
        discoverPeople: "Адамдарды табу",
        messages: "Билдирүүлөр",
        contacts: "Контакттар",
        knock: "Тыкылдатуу",
        connected: "Туташты",
        messagePlaceholder: "Билдирүү...",
        eq: "Эквалайзер",
        look: "Түрү",
        sleep: "Таймер",
        resetFlat: "Баштапкы",
        appAppearance: "Сырткы көрүнүшү",
        sleepTimer: "Уктоо таймери",
        turnOffTimer: "Таймерди өчүрүү",
        whoAreYou: "StreamFlow'го кош келиңиз",
        createProfile: "Дүйнөлүк тыңдоочулар коомчулугунун бир бөлүгү болуу үчүн профиль түзүңүз.",
        displayName: "Сиздин атыңыз",
        age: "Жашыңыз",
        country: "Өлкө",
        city: "Шаар",
        gender: "Жынысы",
        male: "Эркек",
        female: "Аял",
        other: "Башка",
        any: "Кандай болбосун",
        joinCommunity: "Кирүү",
        uploadPhoto: "Сүрөт жүктөө",
        call: "Чалуу",
        calling: "Чалуу...",
        endCall: "Аяктоо",
        videoCall: "Видео чалуу",
        saveContact: "Контакттарга",
        editName: "Атты өзгертүү",
        save: "Сактоо",
        cancel: "Жокко чыгаруу",
        genres: "Жанрлар",
        eras: "Доорлор",
        mood: "Маанай",
        moods: "Маанай",
        favorites: "Тандалган",
        settings: "Жөндөөлөр",
        language: "Тил",
        recording: "Жазылууда...",
        tapToSpeak: "Сүйлөө үчүн басыңыз",
        tapToStop: "Токтотуу үчүн басыңыз",
        failedToLoadStations: "Станцияларды жүктөө ишке ашкан жок.",
        corsWarningVisualizer: "Бул станция үчүн визуализатор жана эквалайзер өчүрүлгөн.",
        chatSettings: "Чат жөндөөлөрү",
        filterBy: "Чыпкалоо",
        ageRange: "Жашы",
        preferredGender: "Тандалган жыныс",
        blockUser: "Блоктоо",
        yellowWarning: "Сары деңгээл",
        redBlock: "Толук блоктоо",
        warningNotice: "Колдонуучуга эскертүү берилди.",
        blockNotice: "Колдонуучу биротоло блоктолду.",
        bannedMessage: "Сиздин аккаунтуңуз убактылуу чектелди (1 күнгө).",
        safetyLevel: "Коопсуздук деңгээли",
        help: "Жардам",
        manual: "Нускама",
        tutorial: "Сабак",
        startTutorial: "Окутууну баштоо",
        skip: "Өткөрүп жиберүү",
        next: "Кийинки",
        gotIt: "Түшүнүктүү!",
        tutorialWelcome: "StreamFlow'го кош келиңиз!",
        tutorialStep1: "Капталдагы менюдан станцияларды жанр же доор боюнча тандай аласыз. Сиздин тандалган каналдар да ушул жерде.",
        tutorialStep2: "Негизги тизмеде миңдеген станциялар бар. Түз эфирди баштоо үчүн каалаган карточканы басыңыз.",
        tutorialStep3: "Төмөндөгү ойноткуч панели учурдагы станцияны көрсөтөт. Бул жерде сиз үндү башкарып, визуализаторду көрө аласыз.",
        tutorialStep4: "Куралдар панелинде эквалайзерди тууралап, теманы өзгертүп же уктоо таймерин кое аласыз.",
        tutorialStep5: "Башка тыңдоочулар менен баарлашыңыз! Адамдарды жашы, шаары же өлкөсү боюнча табуу үчүн чатты колдонуңуз.",
        manualTitle: "Колдонуучунун колдонмосу",
        manualIntro: "StreamFlow — заманбап радио платформа. Тартип жана сый-урмат — биздин негизги баалуулуктарыбыз.",
        manualSection1: "1. Навигация: Жанрларды жана доорлорду тандаңыз. Издөө сүйүктүү толкунуңузду табууга жардам берет.",
        manualSection2: "2. Үн: Биз эң мыкты серверлерди колдонобуз. Эгер станция ойнобосо, бул аймактык чектөөлөрдөн болушу мүмкүн.",
        manualSection3: "3. Жөндөө: Эквалайзер жана темалар тиркемени жекече кылууга мүмкүндүк берет.",
        manualSection4: "4. Баарлашуу кодекси: Эки тарап тең макул болгондо гана ачык баарлашууга жол берилет. Бирок ар бир колдонуучу каалаган убакта башкасын блоктой алат.",
        manualSection5: "5. Катуу тыюулар: Сөгүнүү, сексуалдык зордук-зомбулук, порнография же жылаңачтык өмүр бою блоктоого алып келет.",
        discoveryDrum: "Жаңылыктар барабаны",
        agreeToMeet: "Жолугушууга макул болуу",
        lookingForMatch: "Ылайыктуу түгөй изделүүдө...",
        newMatchFound: "Жаңы дал келүү табылды!",
        match: "Жуп",
        found: "Табылды",
        listenersOnline: "Тыңдоочулар онлайн",
        adjustFilters: "Чыпкаларды тууралоо",
        minAge: "Мин. жаш",
        maxAge: "Макс. жаш",
        search: "Издөө",
        blockConfirm: "Колдонуучуну 24 саатка блоктоо керекпи?",
        soundNotifications: "Үн билдирүүлөрү",
        on: "Күйүк",
        off: "Өчүрүү",
        activeChats: "Активдүү чаттар",
        downloader: "Музыка жүктөөчү",
        hqDownload: "HQ жүктөө",
        communityCode: "Коомчулук кодекси",
        iAgree: "Мен ережелерге макулмун",
        rulesTitle: "Катуу тартип эрежелери",
        rulesIntro: "Бул чатка кирүү менен сиз төмөнкү эрежелерди кабыл аласыз:",
        rule1: "ЖАШ ӨСПҮРҮМДӨРГӨ ТЫЮУ САЛЫНАТ (ТЕК 18+).",
        rule2: "Контентті көзөмөлдөө: Порнографияга тыюу салынат.",
        rule3: "Кылмыштуулук: Курал же баңгизат сатууга тыюу салынат.",
        rule4: "Макулдук жана сый-урмат: Бири-бириңизди сыйлаңыз.",
        visualizer: "Визуализация",
        vizGalaxy: "Галактика",
        vizRings: "Кванттык шакекчелер",
        vizBubbles: "Көбүкчөлөр",
        vizLines: "Неон сызыктары",
        vizBars: "Классика",
        vizDancer: "Бийчи",
        vizTrio: "Үч бийчи",
        vizJourney: "Аалам саякаты"
    }
};
